### ISSUE TITLE
[FEAT] 시큐리티 설정

### ISSUE THREAD

**Issue by gudals-kim** [sail106/back#2]
---
name: "Issue Template"
about: 해당 이슈 생성 템플릿을 사용해 이슈를 생성해주세요.
title: '시큐리티 설정'
labels: '1week'
assignees: 'gudals-kim'

---

## Description ✏
- 시큐리티 설정 및 프로토타입 설계, CICD 공부 및 설계

## Todo 📝
- [x] 이메일 발송 api
- [x] 이메일 인증 api
- [x] 임시 비밀번호 생성 및 이메일 발송 api
- [x] redis 설정 파일 생성
- [x] security 설정

## ETC 📌
- 미루지 말자
