### ISSUE TITLE
[FEAT] WEB RTC 부분 공부 및 설계

### ISSUE THREAD

**Issue by gudals-kim** [sail106/back#3]
---
name: "Issue Template"
about: 해당 이슈 생성 템플릿을 사용해 이슈를 생성해주세요.
title: '[FEAT] WEB RTC 부분 공부 및 설계'
labels: '1week'
assignees: 'junwon9824'

---

## Description ✏
- WEB RTC 부분 공부 및 설계

## Todo 📝
- [ ]  WEB RTC 관련 API 설계
- [ ]  피부 인식 AI 설계
- [ ]  뷰티 인식 AI 설계

## ETC 📌
- 파이팅 합시다
